name: CI

on: [push, pull_request]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run ShellCheck
        run: |
          bash -c 'shopt -s globstar nullglob; shellcheck **/*.sh'

